version: '3.9'

services:
  postgres-database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: klockandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - klockan

  klockan-backend:
    container_name: backend
    image: klockan/backend:latest
    ports:
      - 5209:8080
      - 5001:5001
    depends_on:
      - postgres-database
    networks:
      - klockan

  klockan-frontend:
    container_name: frontend
    image: klockan/frontend:latest
    ports:
      - 4000:4000
      - 80:80
    networks:
      - klockan

  keycloak-server:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.4
    ports:
      - '8443:8443'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DEFAULT_THEME=klockan-theme
    volumes:
      - ./Klockan-Keycloak/config/:/opt/keycloak/data/import
      - ./Klockan-Keycloak/klockan-theme/:/opt/keycloak/themes/klockan-theme
      - ./Klockan-Keycloak/certs/:/opt/keycloak/certs/
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --https-port=8443 --https-certificate-file=/opt/keycloak/certs/keycloak-server.crt.pem --https-certificate-key-file=/opt/keycloak/certs/keycloak-server.key.pem --import-realm'
    networks:
      - klockan

volumes:
  postgres_data:

networks:
  klockan:
    driver: bridge
