version: '3.9'

services:
  postgres-database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: klockandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - klockan

  klockan-backend:
    container_name: backend
    image: klockan/backend:v1
    ports:
      - 5209:8080
    depends_on:
      - postgres-database
    networks:
      - klockan

  klockan-frontend:
    container_name: frontend
    image: klockan/frontend:v1
    ports:
      - 4200:80
    networks:
      - klockan

  keycloak-server:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.4
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DEFAULT_THEME=klockan-theme
    volumes:
      - ./Klockan-Keycloak/config/:/opt/keycloak/data/import
      - ./Klockan-Keycloak/klockan-theme/:/opt/keycloak/themes/klockan-theme
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
    networks:
      - klockan

volumes:
  postgres_data:

networks:
  klockan:
    driver: bridge
