name: Setup SSH for EC2 instance

on:
  push:
    branches:
      - develop

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
      EC2_URL: ${{ secrets.ASW_HOST_DNS }}
      EC2_USERNAME: ${{ secrets.USERNAME }}
    steps:
    - name: Create pem file
      run: echo "${{ secrets.AWS_SSH_KEY }}" | tr -d '\r' > klockan-kp.pem
    - name: Garantizar que la clave no se pueda ver públicamente.
      run: chmod 400 klockan-kp.pem
    - name: SHH client coneect
      run: ssh -i "klockan-kp.pem" ubuntu@ec2-3-12-136-199.us-east-2.compute.amazonaws.com
    - name: accept conections      
      run: yes
