ame: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  
  build:

    runs-on: ubuntu-latest
    environment: secrets
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
        
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker-compose build
    - name: Push to Dockerhub
      run: docker push klockan/cicd-pipeline:latest
