name: Setup SSH for EC2 instance

on:
  push:
    branches:
      - develop

jobs:
 Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
  
    steps:
          - uses: actions/checkout@v2 
          - name: Build & Deploy
            env:
              EC2_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
              EC2_URL: ${{ secrets.ASW_HOST_DNS }}
              EC2_USERNAME: ${{ secrets.USERNAME }}

            
            run: |
              echo "$EC2_SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
              ssh -o StrictHostKeyChecking=no -i private_key ${EC2_USERNAME}@${EC2_URL} '
                sudo exit 0
            
            #   echo "${{ secrets.AWS_SSH_KEY }}" | tr -d '\r' > klockan-kp.pem
            #   chmod 400 klockan-kp.pem
            #   ssh -tt -i "klockan-kp.pem" ubuntu@ec2-3-12-136-199.us-east-2.compute.amazonaws.com
            #     sudo exit 0

        
    
