name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop","main" ]

jobs:
  
  build:
  
    runs-on: ubuntu-latest
    environment: secrets
    steps:
    - uses: actions/checkout@v3
      with: 
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        toke: ${{ secrets.PERSONAL_TOKEN }}
    - name: Init submodule
      run: git submodule init
    - name: update submodule to lates change     
      run:
        git config --global user.email "nicolas.schleicher@jala.university"
        git config --global user.name "NicolasSCJala" 
        git submodule update --remote
    - name: Login Dockerhub
        
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
   
    - name: Build the Docker image
      run: docker-compose build
    - name: Push to Dockerhub
      run: docker push klockan/cicd-pipeline:latest
