name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
   
    steps:

    - name: Connect SHH
      run: ssh -i { secrets.AWS_SSH_KEY } ubuntu@ec2-3-12-136-199.us-east-2.compute.amazonaws.com
      
    
 
